apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: catalogue-service
  name: catalogue-service
spec:
  type: LoadBalancer
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: catalogue-service