apiVersion: v1
kind: Pod
metadata:
  name: build-pod
  labels:
    app: pod
spec:
  containers:
    - name: maven
      image: maven:3.3.9-jdk-8-alpine
      command:
        - cat
      ttyEnabled: true
      terminationMessagePath: "/tmp/my-log"
      terminationMessagePolicy: FallbackToLogsOnError
    - name: docker
      image: docker:19.03
      command:
        - cat
      ttyEnabled: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: helm
      image: lachlanevenson/k8s-helm:v3.1.1
      command:
        - cat
      ttyEnabled: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock