apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: catalogue-service
  name: catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalogue-service
  template:
    metadata:
      labels:
        io.kompose.service: catalogue-service
    spec:
      containers:
      - env:
        - name: RDS_DB_NAME
          value: sql9354505
        - name: RDS_HOSTNAME
          value: "sql9.freesqldatabase.com"
        - name: RDS_PASSWORD
          value: jVFJhDUKt5
        - name: RDS_PORT
          value: "3306"
        - name: RDS_USERNAME
          value: sql9354505
        image: deb538/catalogue:0.0.1-SNAPSHOT
        imagePullPolicy: ""
        name: catalogue-service
        ports:
        - containerPort: 5000
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
