apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: catalogue-service
  name: catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalogue-service
  template:
    metadata:
      labels:
        io.kompose.service: catalogue-service
    spec:
      containers:
      - env:
        - name: RDS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: spring-app-config
              key: RDS_DB_NAME
        - name: RDS_HOSTNAME
          value: "sql9.freesqldatabase.com"
        - name: RDS_PASSWORD
          value: jVFJhDUKt5
        - name: RDS_PORT
          value: "3306"
        - name: RDS_USERNAME
          value: sql9354505
        volumeMounts:
          - name: application-config
            mountPath: "/config"
        image: deb538/catalogue:0.0.1-SNAPSHOT
        imagePullPolicy: ""
        name: catalogue-service
        ports:
        - containerPort: 5000
      restartPolicy: Always
      volumes:
        - name: application-config
          configMap:
            name: spring-app-config
            items:
             - key: application.properties
               path: application.properties
