apiVersion: v1
data:
  application.properties: |-
    #spring.datasource.url=jdbc:h2:mem:testdb
    #spring.datasource.driverClassName=org.h2.Driver
    #spring.datasource.username=sa
    #spring.datasource.password=password
    #spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    #spring.datasource.hikari.connection-timeout=5000
    #spring.datasource.hikari.maximum-pool-size=10
    #spring.h2.console.enabled=true
    #spring.h2.console.settings.trace=false
    spring.profiles.active=jdbc
    spring.jpa.show-sql=true
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.url=jdbc:mysql://${RDS_HOSTNAME:sql9.freesqldatabase.com}:${RDS_PORT:3306}/${RDS_DB_NAME:sql9354505}
    spring.datasource.username=${RDS_USERNAME:sql9354505}
    spring.datasource.password=${RDS_PASSWORD:jVFJhDUKt5}
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
    server.port=5000
    spring.application.name=catalogue-service
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: my-config
--- 
