kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dit # your namespace
  name: pod-reader # Role name will be needed for binding to user
rules:
- apiGroups: ["","apps"] # "" indicates the core API group
  resources: ["deployments", "replicasets", "pods", "pods/log", "pods/portforward", "services", "secrets", "configmaps", "catalogue-service-volume-sec", "catalogue-service-env-configmap"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: dit # your namespace
subjects:
- kind: User
  name: system:anonymous # Name is case sensitive
  apiGroup: ""
- kind: User
  name: system:serviceaccount:default:default # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""